dev_mode: False
seed: 669
operator: "virtual_category"
evaluator: "segmentation"

log:
  prefix: "euup_deeplabv3p"
  comment: "semi"
  log_dir: "./log/"
  summary_interval: 20
  wandb: "SEG-EUUP"
  aim:

data:
  weak_transforms:
    batch_apply:
      normalize:
        - [0.485, 0.456, 0.406]
        - [0.229, 0.224, 0.225]
        - True
        - False
    batch_pad:
      fixed_size: [512, 512]
  strong_transforms:
    batch_apply:
      random_color_jitter:
        - 0.8
        - 0.5
        - 0.5
        - 0.5
        - 0.25
      random_grayscale:
      random_gaussian_blur:
      normalize:
        - [0.485, 0.456, 0.406]
        - [0.229, 0.224, 0.225]
        - True
        - False
      k_random_erase:
        scale: [0.02, 0.4]
        ratio: [0.3, 3.3]
        p: 0.5
    batch_pad:
      fixed_size: [512, 512]

model:
  backbone:
    type: "resnet"
    depth: 101
    strides: [1, 2, 2, 1]
    dilations: [1, 1, 2, 4]
    multi_grid: [2, 4, 8]
    contract_dilation: True
    deep_stem: True
    norm_layer: "SyncBN"
    pretrained: "./cache/resnet101c.pth"
  aspp:
    in_channels: 2048
    inner_channels: 256
    lowlevel_in_channels: 256
    lowlevel_inner_channels: 48
    dilations: [1, 6, 12, 18]
    norm_layer: "SyncBN"
  dropout: 0.
  teacher:
    score_threshold: 0.95
    low_score_threshold: 0.8

solver:
  unreliable_ratio: 0.9
  thresh_init: 0.8
  amp_train: False
  iter_num: 40000
  burnin_iter_num: 1000
  eval_interval: 1000
  ckp_interval: 5000
  ema_momentum: 0.9996
  ema_bn: True
  u_loss_weight: 1
  euup_weight_norm: "adaptive_min"
  lr_multi: 10.0
  optimizer:
    type: "sgd"
    lr: 0.001
    weight_decay: 0.0001
    weight_decay_norm: 0
    weight_decay_bias: 0
    momentum: 0.9
  lr_scheduler:
    type: "poly"
    iter_num: 40000
    power: 0.9
    min_lr: 0.0001
    warmup: True
    warmup_step: 500
    warmup_gamma: 0.001
